server:
  port: 8081
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  application:
    name: simulation
  rabbitmq:
    username: notenger
    password: mCSZSJIq&HZh+3Nk
    addresses: b-91d9fd6b-d716-446f-9b59-ce43c870cfbf.mq.eu-central-1.amazonaws.com:5671

eureka:
  client:
    enabled: false