server:
  port: 8082

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  application:
    name: telematics
  data:
    mongodb:
      host: mongo
      port: 27017
      authentication-database: admin
      database: telematics
      username: notenger
      password: password
  rabbitmq:
    addresses: rabbitmq:5672

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    telematics: telematics.queue
  routing-keys:
    internal-telematics: internal.telematics.routing-key

eureka:
  client:
    enabled: false