server:
  port: 8082

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  application:
    name: telematics
  data:
    mongodb:
      host: mongo
      port: 27017
      authentication-database: admin
      database: telematics
      username: notenger
      password: password
  rabbitmq:
    username: notenger
    password: mCSZSJIq&HZh+3Nk
    addresses: b-91d9fd6b-d716-446f-9b59-ce43c870cfbf.mq.eu-central-1.amazonaws.com:5671

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    telematics: telematics.queue
  routing-keys:
    internal-telematics: internal.telematics.routing-key

eureka:
  client:
    enabled: false