server:
  port: 8082

spring:
  application:
    name: telematics
  data:
    mongodb:
      database: telematics
      port: 27017
  mongodb:
    embedded:
      version: 4.0.2
  rabbitmq:
    addresses: rabbitmq:5672

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2
      databaseDir: ./database

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true